obj-y :=
obj-m :=

src := $(srcroot)/$(curdir)
obj := $(objroot)/$(curdir)

include $(src)/Makefile

# Find all subdirectories we need to descend into, either for built-in objects or for modules
subdir-ym := $(patsubst %/,%, $(filter %/, $(obj-y) $(obj-m)))

# Replace all built-in subdirectory goals with their output archive
obj-y := $(patsubst %/, %/built-in.a, $(obj-y))

# Replace all module subdirectory goals with their output list
obj-m := $(patsubst %/, %/modules.order, $(obj-m))

# Expand $(foo-objs) $(foo-y) etc., by replacing their individuals
suffix-search = $(strip $(foreach s, $3, $($(1:%$(strip $2)=%$s))))
# List composite targets that are constructed by combining other targets
multi-search = $(sort $(foreach m, $1, $(if $(call suffix-search, $m, $2, $3 -), $m)))
# List primitive targets that are compiled from source files
real-search = $(foreach m, $1, $(if $(call suffix-search, $m, $2, $3 -), $(call suffix-search, $m, $2, $3), $m))

# If $(foo-objs), $(foo-y), $(foo-m), or $(foo-) exists, foo.o is a composite object
multi-obj-y := $(call multi-search, $(obj-y), .o, -objs -y)
multi-obj-m := $(call multi-search, $(obj-m), .o, -objs -y -m)
multi-obj-ym := $(multi-obj-y) $(multi-obj-m)

# Replace multi-part objects by their individual parts, including built-in.a from subdirectories
real-obj-y := $(call real-search, $(obj-y), .o, -objs -y)
real-obj-m := $(call real-search, $(obj-m), .o, -objs -y -m)

# Transform everything to be relative to the object directory
real-obj-y	:= $(addprefix $(obj)/,$(real-obj-y))
real-obj-m	:= $(addprefix $(obj)/,$(real-obj-m))
multi-obj-m	:= $(addprefix $(obj)/,$(multi-obj-m))

# Gather dependency files generated by the preprocessor
deps-y := $(patsubst %.o, %.d, $(real-obj-y))
deps-m := $(patsubst %.o, %.d, $(real-obj-m))
deps-ym := $(deps-y) $(deps-m)

-include $(deps-ym)

$(obj)/%.o: $(src)/%.c
	$(Q)mkdir -p $(@D)
	$(Q)$(CC) -MMD -MF $< -o $@

$(call multi_depend, $())

subdir-builtin := $(sort $(filter %/built-in.a, $(real-obj-y)))
subdir-modules := $(sort $(filter %/modules.order, $(real-obj-m)))

$(subdir-builtin): $(obj)/%/built-in.a: $(curdir)/% ;
$(subdir-modules): $(obj)/%/modules.order: $(curdir)/% ;

$(obj)/built-in.a: $(real-obj-y)
	$(Q)rm -f $@
	$(Q)$(AR) cDPrST $@

# Ordinary objects get added to `modules.order`, but subdirectories just have their `modules.order`
# pasted in.
$(obj)/modules.order: $(obj-m)
	$(Q){ $(foreach m, $<, $(if $(filter %/$@, $m), cat $m, echo $m);) :; } >$@

.PHONY: $(subdir-ym)
$(subdir-ym):
	$(Q)$(MAKE) $(build)=$@ \
	need-builtin=$(if $(filter $@/built-in.a, $(subdir-builtin)),1) \
	need-modules=$(if $(filter $@/modules.order, $(subdir-modules)),1) \
	$@

.PHONY: $(curdir)/
$(curdir)/:
	@:

ifdef need-builtin
$(curdir)/: $(obj)/built-in.a
endif

ifdef need-modules
$(curdir)/: $(obj)/modules.order
endif
